### ISSUE TITLE
Fails to add repo if `/etc/yum.repos.d` directory does not exist

### ISSUE THREAD

**Issue by arthurbarr** [chef-cookbooks/yum#144]
The `repository` resource doesn't check to see if `/etc/yum.repos.d` directory already exists.

This caused a problem for me on Ubuntu (I know Ubuntu isn't technically supported, but I have a bunch of RPMs to install, and adding a local yum repo seemed like the way to go).

**Comment by jblaine** [comment]
What does it do when the directory doesn't exist? If it throws an exception, I'd argue that's correct behavior because that means the host (a supported platform that is) is in a very weird state. If it does something else like silently fail, then that's probably not right and it probably _should_ be throwing an exception.

Either isn't the answer you're looking for :)

If you're using yum on an unsupported platform you should just do whatever it takes to make that work (in this case a wrapper cookbook that calls `directory` first).

But hey, I'm just someone passing through with an opinion.

**Comment by arthurbarr** [comment]
Yes, creating a directory first is exactly what I did.  As I said, I know Ubuntu isn't technically supported, but it does seem to work fine on Ubuntu, except for this.  It seems to me that adding the directory creation (if missing) would be a nice thing to add to this cookbook, but others may disagree.

**Comment by tas50** [comment]
Since our supported platforms for this cookbook are RHEL based platforms I think we should pass on fixing this issue. Managing the directory only causes additional problems if the permissions vary at all between yum based distros.
