### ISSUE TITLE
how to download yum rpm to intel's machine and install in another ARM64 machine

### ISSUE THREAD

**Issue by JohnGW05** [chef-cookbooks/yum#170]
hi,
   Could i download yum rpm to intel's machine and install in another ARM64 machine？ because i have a x86 machine which can surfer internet and a arm64 machine which cannot surfer internet, but i need use yum to install massive RPM to ARM64. wish your response, thank you very much

**Comment by iennae** [comment]
Hi @JohnGW05, It's unclear whether you are talking about the chef-cookbook yum or just using yum in general. You can create your own local yum repository within your organization. You can then configure your systems to query that local yum repository. You would just need to manage your local yum repository and keep it updated. If your problem is managing that local yum repository, this is not the right forum to get support for that. If you have future questions about using chef and this yum cookbook please do open up a new issue with the relevant information.
